# Override configuration from https://github.com/jenkins-x/jenkins-x-platform/blob/master/jenkins-x-platform/values.yaml
chartmuseum:
  persistence:
    size: 20Gi
jenkins:
  Persistence:
    Size: 20Gi
monocular:
  mongodb:
    persistence:
      size: 20Gi
nexus:
  persistence:
    size: 20Gi
tekton:
  pvc:
    size: 20Gi
