# Override configuration from https://github.com/jenkins-x/jenkins-x-platform/blob/master/jenkins-x-platform/values.yaml
jenkins-x-platform:
  PipelineSecrets:

    # lets enable ECR docker builds
    DockerConfig: |-
      {
{{- if .Requirements.cluster.registry }}
        "credHelpers": {
          "{{ .Requirements.cluster.registry }}": "ecr-login"
        }
{{- else }}
        "credsStore": "ecr-login"
{{- end }}
      }
      
docker-registry:
  enabled: false    
