velero:
{{- if and (hasKey .Requirements "velero") (hasKey .Requirements.velero "namespace") }}
  {{- if .Requirements.velero.namespace }}
  enabled: true
  schedule: {{ .Requirements.velero.schedule | default "0 * * * *" | quote }}
  ttl: {{ .Requirements.velero.ttl | default "720h0m0s" }}
  {{- else }}
  enabled: false
  {{- end }}
{{- else }}
  enabled: false
{{- end }}
