apiVersion: jenkins.io/v1
kind: SourceRepositoryGroup
metadata:
  name: default-group
spec:
  scheduler:
    apiVersion: jenkins.io/v1
    kind: Scheduler
    name: default-scheduler
  repositories: []
