external-dns:
  enabled: {{ .Requirements.ingress.externalDNS }}
  sources:
  - ingress
{{- if eq .Requirements.cluster.provider "eks"}}
  provider: aws
  aws:
    region: {{ .Requirements.cluster.region}}
  securityContext:
    fsGroup: 65534
{{- else if eq .Requirements.cluster.provider "gke"}}
  provider: google
  google:
    serviceAccountSecret: external-dns-gcp-sa
 {{- if hasKey .Requirements.cluster "project" }}
    project: "{{ .Requirements.cluster.project }}"
 {{ end }}
{{- end}}

  rbac:
    create: true
  domainFilters:
{{- range .Requirements.environments }}
 {{- if .ingress.domain }}
  - "{{ .ingress.domain }}"
  {{- end }}
{{- end }}
