# Override configuration from https://github.com/jenkins-x/jenkins-x-platform/blob/master/jenkins-x-platform/values.yaml
jenkins-x-platform:
  PipelineSecrets:

    # lets enable ECR docker builds
    DockerConfig: |-
      {
        "credsStore": "ecr-login"
      }
      
docker-registry:
  enabled: false        
